/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
// import { motion } from 'framer-motion'


export function Lola(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/lola.glb')
    const { actions } = useAnimations(animations, group);
    const [openAccordion, setOpenAccordion] = useState(null); // Track the currently open accordion

    useEffect(() => {
        actions['Idle'].play()
    }, [])

    const handleAccordionClick = (accordionIndex) => {
        setOpenAccordion(openAccordion === accordionIndex ? null : accordionIndex);
    };

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group name="Lola_New_Body">
                        <skinnedMesh
                            name="Mesh"
                            geometry={nodes.Mesh.geometry}
                            material={materials.Body}
                            skeleton={nodes.Mesh.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_1"
                            geometry={nodes.Mesh_1.geometry}
                            material={materials.Face}
                            skeleton={nodes.Mesh_1.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_2"
                            geometry={nodes.Mesh_2.geometry}
                            material={materials.Hand}
                            skeleton={nodes.Mesh_2.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_3"
                            geometry={nodes.Mesh_3.geometry}
                            material={materials.Material__24}
                            skeleton={nodes.Mesh_3.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_4"
                            geometry={nodes.Mesh_4.geometry}
                            material={materials.Material__104}
                            skeleton={nodes.Mesh_4.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_5"
                            geometry={nodes.Mesh_5.geometry}
                            material={materials.Hate}
                            skeleton={nodes.Mesh_5.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_6"
                            geometry={nodes.Mesh_6.geometry}
                            material={materials.Lola}
                            skeleton={nodes.Mesh_6.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_7"
                            geometry={nodes.Mesh_7.geometry}
                            material={materials['Material #135']}
                            skeleton={nodes.Mesh_7.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_8"
                            geometry={nodes.Mesh_8.geometry}
                            material={materials['Material #147']}
                            skeleton={nodes.Mesh_8.skeleton}
                        />

                        {/* Attach Html to follow the model */}
                        {/* <Html position={[0, -500, -300]} center style={{ zIndex: 1 }}> */}
                        {/* <div className="flex flex-col gap-2 ">
                                <div className="w-96 bg-white p-3 text-xs">
                                    (hustet) Lola hustet... Puh, die Abgase der Autos verschmutzt die Luft. Es stinkt und ich bekomme kaum Luft!
                                </div> */}
                        {/* Accordion 1 */}
                        {/* <div onClick={() => handleAccordionClick(1)} className="cursor-pointer p-2 bg-white">
                                    Warum musst du so husten?
                                </div>
                                {openAccordion === 1 && (
                                    <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: "auto", opacity: 1 }}
                                        exit={{ height: 0, opacity: 0 }}
                                        className="p-2 border bg-gray-200"
                                    >
                                        Content for Accordion 1
                                    </motion.div>
                                )} */}

                        {/* Accordion 2 */}
                        {/* <div onClick={() => handleAccordionClick(2)} className="cursor-pointer p-2 bg-white border-b">
                                    Lass uns das Gelernte einmal zusammenfassen!
                                </div>
                                {openAccordion === 2 && (
                                    <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: "auto", opacity: 1 }}
                                        exit={{ height: 0, opacity: 0 }}
                                        className="p-2 border bg-gray-200"
                                    >
                                        Content for Accordion 2
                                    </motion.div>
                                )}
                            </div> */}
                        {/* </Html> */}
                    </group>
                    <primitive object={nodes.Lola_Pelvis} />
                    <primitive object={nodes.Lola_LPlatform} />
                    <primitive object={nodes.Lola_RPlatform} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/lola.glb')
